name: Deploy page to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install --global surge

    - name: Deploy
      run: |
        surge --project ./ --domain parcialsite.surge.sh --token e435191426bf7a01dad4644ad481f5e5